# Generated by Django 5.1.7 on 2026-03-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('mi', models.CharField(blank=True, max_length=10, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_visit', models.DateField()),
                ('company', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
